version: "3.7"
services:
  postgres:
    image: postgres:13.2-alpine
    environment:
      - POSTGRES_PASSWORD=test_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  api:
    build:
      context: processes/api
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    expose: 
        - "5000"
    environment:
      - DATABASE_URL="postgres://postgres:test_db@127.0.0.1:5432/"
      - PORT=5000
  ui:
    build: 
      context: processes/ui
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    expose: 
      - "80"
